In [2]:
import numpy as np

In [19]:
a = np.arange(0,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a.shape, a.diagonal()

((3, 4), array([ 0,  5, 10]))

In [24]:
a.ndim

2

In [26]:
a.dtype

dtype('int32')

In [28]:
a.dtype.name

'int32'

In [30]:
a.itemsize # memory size

4

In [32]:
a.size

12

In [34]:
type(a)

numpy.ndarray

In [39]:
list(a.flatten())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [42]:
b= np.array([6,7,8])
b

array([6, 7, 8])

In [43]:
type(b)

numpy.ndarray

In [45]:
b.dtype

dtype('int32')

In [53]:
x=np.zeros([2,4])
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
x.shape, x.ndim

((2, 4), 2)

In [63]:
empty = np.empty([2,3])
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
np.arange(1,5,2)

array([1, 3])

In [74]:
x = np.linspace(1,4,8) #8 Numbers between 1-4
x

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

# printing Arrays

In [75]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [77]:
b = np.arange(12).reshape(4,3)
print(b);b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])