In [1]:
import numpy as np
import pandas as pd

In [2]:
test_array = np.array([1,4,5,8], float)

In [4]:
test_array

array([1., 4., 5., 8.])

In [6]:
# numpy는 np.array 함수를 활용하여 배열을 생성함 è ndarray
#- numpy는 하나의 데이터 type만 배열에 넣을 수 있음
#- List와 가장 큰 차이점, Dynamic typing not supported
#- C의 Array를 사용하여 배열을 생성함

In [7]:
# Array Creation
test_array = np.array([1,4,5,6])
test_array

array([1, 4, 5, 6])

In [9]:
test_array = np.array([1,2,3,54], float)
test_array

array([ 1.,  2.,  3., 54.])

In [10]:
type(test_array[1])

numpy.float64

In [12]:
# If other data type passed the the array will changed to passed data type if Possible
test_array = np.array([1,3,4,'5'],dtype=str)
test_array

array(['1', '3', '4', '5'], dtype='<U1')

In [14]:
np.array([1.000,3,4,'5'],dtype=int)

array([1, 3, 4, 5])

In [15]:
np.array([1.000,3,4,'5'],dtype=float)

array([1., 3., 4., 5.])

### Array Shape (Matrix)

In [16]:
matrix = [[1,2,5,7],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [21]:
# Array Shape (3 rd order tensor)
tensor = np.array([[1,2,3,4],[1,2,5,6]])
tensor.shape

(2, 4)