https://www.tensorflow.org/api_docs/python/tf/argsort

In [29]:
import tensorflow as tf
import numpy as np

#### argsort

#### argsort

#### argsort

In [8]:
tf.argsort?

Returns the indices of a tensor that give its sorted order along an axis.

For a 1D tensor, `tf.gather(values, tf.argsort(values))` is equivalent to
`tf.sort(values)`. For higher dimensions, the output has the same shape as
`values`, but along the given axis, values represent the index of the sorted
element in that slice of the tensor at the given position.

python`tf.argsort(
values=, axis = -1 , direction  = "ASCENDING", stabel = False, name = None
)`

In [4]:
# usage:
a = [1,10,26.9, 2.8, 166,32 , 62.3]

b = tf.argsort(a, axis = -1 , direction = "ASCENDING", stable = False, name = None)
c = tf.keras.backend.eval(b)

In [7]:
c

array([0, 3, 1, 2, 5, 6, 4])

#### tf.batch_to_space

In [ ]:
# tf.batch_to_space(input, block_shape, crops, name = None)



#### tf.bitcast

In [9]:
# Bitcats a tensor from one type to another without copying data
# tf.bitcast(input, type, name = None)

# tf.cast() and tf.bitcast() work differently when real dtype is casted as a complex dtype.

In [15]:
a = [1,2,3.]

# equality_bitcast = tf.bitcast(a,tf.complex128)
# The abhove code will raise error as 
# Cannot bitcast from 1 to 18 [Op:Bitcast]

equality_cast = tf.cast(a, tf.complex128)
print(equality_cast)

test = tf.cast(a, tf.int16)
print(test.)

tf.Tensor([1.+0.j 2.+0.j 3.+0.j], shape=(3,), dtype=complex128)
tf.Tensor([1 2 3], shape=(3,), dtype=int16)


In [16]:
# Example 2

In [22]:
x = [1., 2, 3]
y = [0., 2., 3.]
equality= tf.equal(x,y)
print(equality)

tf.Tensor([False  True  True], shape=(3,), dtype=bool)


In [24]:
equality_cast = tf.cast(equality, tf.float32)
print(equality_cast)

tf.Tensor([0. 1. 1.], shape=(3,), dtype=float32)


In [26]:
equality_bit_cast = tf.bitcast(equality_cast, tf.uint8)
print(equality_bit_cast)

tf.Tensor(
[[  0   0   0   0]
 [  0   0 128  63]
 [  0   0 128  63]], shape=(3, 4), dtype=uint8)


In [27]:
# ** Bitcast is implemented as a low-level cast, so machines with different endian orderings will give different results.

#### tf.boolean_mask

In [34]:
# Apply boolean_mask to tensor
# tf.boolean_mask(tensor, mask, axis = None, name = 'boolean_mask')
# Numpy equivalents is tensor[mask]

# 1 d example
tensor = [0,1,2,3]
mask = np.array([True, False, True, False])
tf.boolean_mask(tensor,mask).numpy()

array([0, 2])