In [1]:
import tensorflow as tf

In [2]:
# Load and prepare Mnist dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
x_train, x_test =  x_train/255.0 , x_test/ 255.0

In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
28 *28 

784

In [6]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
   ])
# Number of output is 10

In [7]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.35119665,  0.25084603,  0.37204033, -0.7286056 , -0.554873  ,
        -0.1819074 ,  0.4290492 ,  0.0780657 ,  0.20761555,  0.45981005]],
      dtype=float32)

In [8]:
# The tf.nn.softmax function converts these logits to "probabilities" for each class
tf.nn.softmax(predictions).numpy()

array([[0.12377656, 0.11195841, 0.1263836 , 0.04204228, 0.05001928,
        0.07262971, 0.13379791, 0.09419312, 0.10722152, 0.13797761]],
      dtype=float32)

In [9]:
# The losses.SparseCategoricalCrossentropy loss takes a vector of logits and 
# and a True index 
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
model.compile(optimizer="adam",
             loss = loss_fn,
             metrics=["accuracy","mae"])

In [11]:
model.fit(x_train, y_train, epochs=10)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 7s 112us/sample - loss: 0.2943 - accuracy: 0.9136 - mae: 6.1687
Epoch 2/10
60000/60000 [==============================] - 7s 108us/sample - loss: 0.1420 - accuracy: 0.9589 - mae: 7.1395
Epoch 3/10
60000/60000 [==============================] - 6s 104us/sample - loss: 0.1066 - accuracy: 0.9679 - mae: 7.9470
Epoch 4/10
60000/60000 [==============================] - 6s 108us/sample - loss: 0.0868 - accuracy: 0.9736 - mae: 8.6035
Epoch 5/10
60000/60000 [==============================] - 6s 102us/sample - loss: 0.0738 - accuracy: 0.9766 - mae: 9.2150
Epoch 6/10
60000/60000 [==============================] - 6s 104us/sample - loss: 0.0653 - accuracy: 0.9801 - mae: 9.8875
Epoch 7/10
60000/60000 [==============================] - 6s 105us/sample - loss: 0.0579 - accuracy: 0.9812 - mae: 10.4310
Epoch 8/10
60000/60000 [==============================] - 6s 103us/sample - loss: 0.0525 - accuracy: 0.9830 - mae: 11.0129

In [12]:
model.evaluate(x_test,y_test, verbose=2)

10000/10000 - 1s - loss: 0.0768 - accuracy: 0.9778 - mae: 12.2526


[0.07683638468979626, 0.9778, 12.252605]

In [13]:
# The image classifier is now trained to ~98 % accoracy on this dataset.
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:2])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[5.0179066e-10, 1.5222898e-11, 1.1720988e-08, 3.2410546e-05,
        1.1725948e-16, 1.9395520e-10, 9.6985066e-20, 9.9996746e-01,
        5.4499516e-10, 7.1733226e-08],
       [9.6333030e-10, 6.6416948e-07, 9.9999917e-01, 9.5410737e-09,
        2.5070169e-22, 4.8774529e-10, 3.7294352e-11, 4.3225158e-19,
        1.7336458e-07, 9.3547717e-19]], dtype=float32)>