In [1]:
import tensorflow as tf
import numpy as np

#### tf.variables

In TensorFlow the differences between **constants** and **variables** are that when you declaresome 
Constant, its value can't be changed in the future( also the initialization should be with a value)
not with operation

``` tf.Variables(initial_value = None, trainable = None, validate_shape = True, caching_device = None,
name = None, variable_def = None, dtype = None, import_scope = None, constraint = None, 
synchronization = tf.VariableSynchronization.AUTO, aggregration  = tf.compat.v1.VariableAggregation.NONE, shape = None) ```

In [ ]:
v= tf.Variable(1)
print(v)
print(v.numpy())

print(v.assign_add(10)) # Add value to tensor v
print(v.numpy())

In [ ]:
v  = tf.Variable(1., shape = tf.TensorShape(None))
v.assign([[1.]])

In [ ]:
# Just like any Tensor, variables created with Variable() can be used as inputs
# to operations . 
w = tf.Variable([[1.],[2.]])
x = tf.constant([[3.,4]])
print(w,"\n",x)

tf.matmul(w,x).numpy()

# For Operation same dtype must be assigh

In [ ]:
tf.sigmoid(w+x)

When building a machine learning model it is often convenient to distinguish between variables holding trainable model parameters and other variables such as a step variable used to count training steps. To make this easier, the variable constructor supports a trainable=<bool> parameter. tf.GradientTape watches trainable variables by default:

In [ ]:
with tf.GradientTape(persistent=True) as tape:
    trainable = tf.Variable(1.0)
    non_trainable = tf.Variable(2., trainable = False)
    x1 = trainable * 2
    x2 = non_trainable *3.

tape.gradient(x1,trainable)

In [ ]:
assert tape.gradient(x2, non_trainable) is None

In [ ]:
# Variables are automatically tracked when assigned to attributes of types inheriting from tf.Module
m = tf.Module()  # class
m.v = tf.Variable([1.])
m.trainable_variables

In [ ]:
# This tracking then allows saming variables to training checkpoints or to 
# SaveModels which include serialized TensorFlow graphs

In [ ]:
# variables are often captured and manipulated by tf.functions .
# This works the same way the un-decorated function would have
v = tf.Variable(1.)
read_and_decrement = tf.function( lambda : v.assign_sub(0.1)) # Substract
read_and_decrement()

In [ ]:
read_and_decrement().numpy()

In [ ]:
class M(tf.Module):
    "This class will return square of tensor"
    @tf.function
    def __call__(self,x):
        if not hasattr(self,"v"): 
            self.v = tf.Variable(x)
        return self.v * x

m = M()

In [ ]:
print(m(2.))

print(m(3.))

print(v.numpy())
m.v.numpy()

##### Methods

###### __abs__
abs(x)

In [ ]:
# __abs__(x, name = None)
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

###### __add__
###### __and__
###### __div__
###### __eq__
###### __floordiv__
###### __ge__
function (x,y)

In [ ]:
x = tf.constant([5,4,6,7])
y = tf.constant([5,2,5,10])

tf.math.greater_equal(x,y).numpy()

In [ ]:
tf.equal(x,y).numpy()

In [ ]:
tf.add(x,y).numpy() # Element wise

In [ ]:
tf.divide(x,y) # Element wise

In [ ]:
tf.compat.v1.div(x,y)

In [ ]:
tf.math.greater_equal(x,y)

In [ ]:
tf.greater_equal(x,y)

In [ ]:
import tensorflow as tf
A = tf.Variable([[1,2,3],
                [4,5,6],
                [7,8,9]], dtype = tf.float32)

In [ ]:
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    print(sess.run(A[:2,:2]))
    
    op = A[:2,:2].assign(22.*tf.ones((2,2)))
    print(sess.run())

In [ ]:
# __gt__(x,y,name = None)
x = tf.constant([5, 4, 6])
y = tf.constant([5, 2, 5])

tf.math.greater(x,y).numpy()

In [ ]:
x = tf.constant([5, 4, 6])
y = tf.constant([5])

tf.math.greater(x,y).numpy()

###### __invert__

In [ ]:
tf.math.logical_not(tf.constant([True, False]))

###### __iter__
###### __le__
###### __

__le__(x,y,name = None)
###### Returns the truth value of (x<=y) element-wise.

In [5]:
x = tf.constant([5,4,6])
y = tf.constant([5])

tf.math.less_equal(x,y).numpy() # Element wise comparison

array([ True,  True, False])

In [6]:
x = tf.constant([5,4,6])
y = tf.constant([5,6,6])

tf.math.less_equal(x,y)

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True,  True,  True])>

In [7]:
# __lt__ Less than
x = tf.constant([5,4,6])
y = tf.constant([5])

tf.math.less(x,y)

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False,  True, False])>

In [9]:
x = tf.constant([5,4,6])
y = tf.constant([5,6,7])

tf.math.less(x,y).numpy()

array([False,  True,  True])

In [10]:
# __matmul__(x,y)
# Multiply Matrix a by Matrix b, producing a * b
a = tf.constant([1,2,3,4,5,6],shape=[2,3])
print(a.numpy())

[[1 2 3]
 [4 5 6]]


In [11]:
b = tf.constant([7,8,9,10,11,12],shape=[3,2])
b.numpy()

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [16]:
# A Batch matrix multiplication with batch shape [2]
a = tf.constant(np.arange(1,13,dtype = np.int32),shape=[2,2,3])
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [17]:
b = tf.constant(np.arange(13,25,dtype = np.int32), shape= [2,3,2])
b

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])>

In [18]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]])>

In [19]:
# Since Python >= 3.5 @ Operator is supported
# In Tensorflow it simply calls the tf.matmul()

In [20]:
d = a@b

In [21]:
d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]])>

In [22]:
# __mod__ 
# __mod__(x,y) # Returns element wise remainder of division. When x<0 xor y<0
# e.g. floor(x/y)*y +mod (x,y) = x

In [23]:
# __mul__(x,y) # Dispatches cwise mul for "DenseDense" and "DenseSparse"
# __mul__(x,y)

# __ne__ # Compares two variables element-wise for equality.
# __ne__(other)

# __neg__ # Computes numerical negative value element-wise
# y = -x

# __or__(x,y)


# __pow__(x,y)
# Computes the power of one value to  another

In [24]:
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[8,16],[2,3]])

tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]])>

In [25]:
# __radd__(y,x)  # Dispatches to add for strings and add_v2 for all other types
# __rand__(y,x)  # Returns the truth value of x AND y Element-wise
# __rdiv__(y,x) # Divide 2 values using Python 2 Semantics
# __rfloordiv__(y,x)  # Divides x/y elementwise, rounding toward the most negative integer.
# __rmatmul__(y,x) # Multiplies matrix a by matrix b, producing a*b

In [26]:
a = tf.constant([1,2,3,4,5,6], shape=[2,3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [28]:
b = tf.constant([7,8,9,10,11,12],shape=[3,2])
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [30]:
c = tf.matmul(a,b)  # Matrix Multiplication
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [32]:
# A batch multiplication with batch shape [2]
a = tf.constant(np.arange(1,13,dtype = np.int32), shape=[2,2,3])
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [33]:
b = tf.constant(np.arange(13,25, dtype = np.int32), shape=[2,3,2])
b

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])>

In [35]:
c = tf.matmul(a,b)
c

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]])>

In [36]:
a@b # For Python Greater than 3.5

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]])>

In [37]:
# __rmod__(y,x)   # Returns element wise remainder of division. When x < 0 xor y<0 is true
# __rmod__(y,x) # Returns the truth value of x Or y element-wise

# __rpow__(y,x)  # Computes the power of one value to another
# 

In [39]:
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]])>

In [40]:
# __rsub__(y,x) # Returns y-x element wise

# __rtruediv__ # __rtruediv__(y,x)
# __rxor__(y,x)

In [41]:
a = tf.constant([True])
b = tf.constant([False])
tf.math.logical_or(a,b)

<tf.Tensor: shape=(1,), dtype=bool, numpy=array([ True])>

In [43]:
c = tf.constant([True])
y = tf.constant([False, True, True, False])

tf.math.logical_xor(c,y)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False, False,  True])>

In [45]:
y = tf.constant([True, True, False, False])
x = tf.constant([False, True, False, True])

tf.math.logical_xor(y,x)  # Not ( Opposite)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False, False,  True])>

In [46]:
# __sub__(x,y)
# __truediv__(x,y)
# __xor__(x,y)

In [47]:
a = tf.constant([True])
b = tf.constant([False])
tf.math.logical_xor(a,b)

<tf.Tensor: shape=(1,), dtype=bool, numpy=array([ True])>

#### Assign

**Assign**(value, use_locking = False, name = None, read_value = True) <br>
` Assigns a new value to the variable` <br>
` assign(self, value)`

**assign_add(data,..)** <br>
**assign_sub(data,,,)**

**batch_scatter_update**

**eval(sessiion = None)** <br>
In a session, computes and returns the value of this variable. <br>
This is not a graph construction method, it does not add ops to the graph

In [50]:
v = tf.Variable([1,2])
init = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init)
    # Usage passing the session explicitly
    print(v.eval(sess))
    # Usage with teh default session,. The "with" block
    # above makes "sess" the default session
    print(v.eval)

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [51]:
# get_shape()
# https://www.tensorflow.org/api_docs/python/tf/Variable
# Remaining is follow the link  