## tf.keras.activations

##### Functions
###### deserialize(....)
Returns activations function denoted by input string.

In [1]:
# tf.keras.activations.deserialize(name, custom_objects = Nonee)
import tensorflow as tf
from tensorflow.keras.activations import deserialize

In [4]:
deserialize("linear")

<function tensorflow.python.keras.activations.linear(x)>

In [5]:
deserialize("sigmoid")

<function tensorflow.python.keras.activations.sigmoid(x)>

In [14]:
#deserialize("krihs")
# Fore More Information
deserialize?

###### tf.keras.activations.elu
Exponential linear Unit

In [15]:
# tf.keras.activations.elu(x, alpha = 1.0)
# The exponential linear activation : if x>0 and alpha * (exp(x)-1) if x <0


###### tf.keras.activations.exponential(x)

In [19]:
a = tf.constant([-3,-1.0,0.,1.0,3.0], dtype=tf.float32)
b = tf.keras.activations.exponential(a)
a

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-3., -1.,  0.,  1.,  3.], dtype=float32)>

In [21]:
b

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 0.04978707,  0.36787945,  1.        ,  2.7182817 , 20.085537  ],
      dtype=float32)>

In [22]:
# Tensor with exponential activation : exp(x) Tensor will be of same shape and dtype of input x


###### tf.keras.acctivations.get(identifier)

In [24]:
# identifier --> Function or string
# Returns Activation function denoted by input
# Linear activation function if input is None

In [25]:
tf.keras.activations.get("softmax")

<function tensorflow.python.keras.activations.softmax(x, axis=-1)>

In [29]:
tf.keras.activations.get(None) # None will linear activation

<function tensorflow.python.keras.activations.linear(x)>

In [30]:
tf.keras.activations.get(abs)

<function abs(x, /)>

###### tf.keras.activations.hard_sigmoid(x)
`Faster to compute than sigmoid activation`

In [31]:
a = tf.constant([-3.0, -1.0 , 0, 1.0 , 3.0], dtype=tf.float32)
b = tf.keras.activations.hard_sigmoid(a)

In [34]:
b
# https://www.tensorflow.org/api_docs/python/tf/keras/activations/hard_sigmoid

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0. , 0.3, 0.5, 0.7, 1. ], dtype=float32)>

###### tf.keras.activations.linear(x) 
`Linear activation Function`

In [37]:
a = tf.constant([-3, -1.0 , 0.0 , 1.0 , 3.0], dtype=tf.float32)
b = tf.keras.activations.linear(a)
b.numpy()

array([-3., -1.,  0.,  1.,  3.], dtype=float32)

###### tf.keras.activations.relu(x, alpha =0.0, max_value = None, threshold =0 )
This returns the standard ReLU activations: max(x,0), the element-wise maximim of 0 and the input tensor.

In [46]:
foo = tf.constant([-10, -5, 0.0 , 5, 10], dtype=tf.float16)
tf.keras.activations.relu(foo).numpy()

array([ 0.,  0.,  0.,  5., 10.], dtype=float16)

In [39]:
tf.keras.activations.relu(foo, alpha=0.5,).numpy()

array([-5. , -2.5,  0. ,  5. , 10. ], dtype=float16)

In [41]:
tf.keras.activations.relu(foo, max_value=5).numpy() # maximum up to 5

array([0., 0., 0., 5., 5.], dtype=float16)

In [51]:
#tf.keras.activations.relu(foo, threshold=5) # Ignore upto 5
#tf.keras.activations.relu(foo, threshold=4)

In [52]:
# alpha = A float that governs the slope for values lower than the threshold
# max_value = A float that sets the saturation threshold (the largest value the function will return).
# threshold = A float giving the threshold value of the activation function 
    # below which values will be damped or set to zero

###### selu
**Scaled Exponential Linear Unit (SELU)**

In [54]:
n_classes = 10 # 10_class Problem
from tensorflow.python.keras.layers import Dense

model = tf.keras.Sequential()

model.add(Dense(64, kernel_initializer = "lecun_normal",
         activation = "selu", input_shape = (28,28,1)))

In [55]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 28, 28, 64)        128       
Total params: 128
Trainable params: 128
Non-trainable params: 0
_________________________________________________________________


In [56]:
## Add layer
model.add(Dense(32, kernel_initializer = "lecun_normal", activation = "selu"))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 28, 28, 64)        128       
_________________________________________________________________
dense_2 (Dense)              (None, 28, 28, 32)        2080      
Total params: 2,208
Trainable params: 2,208
Non-trainable params: 0
_________________________________________________________________


In [57]:
model.add(Dense(16,kernel_initializer = "lecun_normal", activation = "selu"))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 28, 28, 64)        128       
_________________________________________________________________
dense_2 (Dense)              (None, 28, 28, 32)        2080      
_________________________________________________________________
dense_3 (Dense)              (None, 28, 28, 16)        528       
Total params: 2,736
Trainable params: 2,736
Non-trainable params: 0
_________________________________________________________________


In [58]:
model.add(Dense(n_classes, activation = "softmax"))

In [59]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 28, 28, 64)        128       
_________________________________________________________________
dense_2 (Dense)              (None, 28, 28, 32)        2080      
_________________________________________________________________
dense_3 (Dense)              (None, 28, 28, 16)        528       
_________________________________________________________________
dense_4 (Dense)              (None, 28, 28, 10)        170       
Total params: 2,906
Trainable params: 2,906
Non-trainable params: 0
_________________________________________________________________


######  https://www.tensorflow.org/api_docs/python/tf/keras/activations/selu


In [60]:
# serialize
# returns name attribute (__name__) of Function

In [ ]:
# tf.keras.activation.serialize(activation)

In [61]:
tf.keras.activations.serialize(tf.keras.activations.tanh)

'tanh'

In [62]:
tf.keras.activations.serialize(tf.keras.activations.sigmoid)

'sigmoid'

In [65]:
# tf.keras.activations.serialize("abcd")

###### tf.keras.activations.sigmoid(x)

In [66]:
# Applies the sigmoid activation function. The sigmoid function is defined as 1 divided by (1+exp(-x))
# Its Curve like S and  is like a smoothed version fo Heaviside Unit Step Function.
# Sigmoid is equivalent to a 2-element Softmax, where the second element is assumed to be zero

In [68]:
a = tf.constant([-20, -1.0 , 0.0 , 1.0 , 20], dtype=tf.float32)
b = tf.keras.activations.sigmoid(a)
b.numpy()

array([2.0611537e-09, 2.6894143e-01, 5.0000000e-01, 7.3105860e-01,
       1.0000000e+00], dtype=float32)

In [69]:
# Returns --> Tensor with the sigmoid activation : (1.0/(1.0+ exp(-x)))
# Tensor will be of same shape and dtype of input x

###### tf.keras.activations.softmax

In [71]:
#tf.keras.activations.softmax(x, axis=1)

###### tf.keras.activations.softsign(x)

In [72]:
# The softsign activation : x/(abs(x)+1)

In [74]:
#tf.keras.activations.swish(x)

###### tf.keras.activations.tanh(x)

In [75]:
a = tf.constant([-3.0, -1.0 , 0.0 , 1.0 , 3.0])
b = tf.keras.activations.tanh(a)

b.numpy()

array([-0.9950547, -0.7615942,  0.       ,  0.7615942,  0.9950547],
      dtype=float32)